import type { BacklinkProfileInput } from "./backlink-fixture-normalization.js";

const cleanRelations = {
  dofollow: true,
  nofollow: false,
  sponsored: false,
  ugc: false,
} as const;

export const P5_5_FIXTURE_OBSERVED_AT = "2026-09-18T00:00:00.000Z" as const;
export const P5_5_FIXTURE_REFERENCE_TIME = "2026-09-18T12:00:00.000Z" as const;

export const P5_5_BASELINE_OWNED_PROFILE: BacklinkProfileInput = {
  targetDomain: "Example.TEST.",
  summary: {
    authority: 58,
    referringDomains: 5,
    backlinks: 9,
    dofollowReferringDomains: 3,
    nofollowReferringDomains: 2,
    sponsoredReferringDomains: 0,
    ugcReferringDomains: 1,
    newReferringDomains30d: null,
    lostReferringDomains30d: null,
  },
  referringDomains: [
    {
      domain: "BeautyJournal.EXAMPLE.",
      authority: 76,
      backlinks: 3,
      relations: cleanRelations,
      firstSeenAt: "2026-02-12T00:00:00.000Z",
      lastSeenAt: "2026-09-10T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "backlink_count",
      anchors: [
        { text: "Diamond Shelf", count: 2, classification: "brand" },
        { text: "luxury fragrance retailer", count: 1, classification: "partial" },
      ],
      targetUrls: [
        "HTTPS://Example.TEST:443/collections/fragrance?b=2&a=1#reviews",
        "https://example.test/",
      ],
    },
    {
      domain: "perfumeweekly.example",
      authority: 64,
      backlinks: 2,
      relations: cleanRelations,
      firstSeenAt: "2026-04-03T00:00:00.000Z",
      lastSeenAt: "2026-07-20T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "https://example.test", count: 2, classification: "url" }],
      targetUrls: ["https://example.test/"],
    },
    {
      domain: "shoppingforum.example",
      authority: 41,
      backlinks: 1,
      relations: { dofollow: false, nofollow: true, sponsored: false, ugc: true },
      firstSeenAt: "2026-01-15T00:00:00.000Z",
      lastSeenAt: "2026-05-01T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "this fragrance store", count: 1, classification: "generic" }],
      targetUrls: ["https://example.test/products/sample-product"],
    },
    {
      domain: "styleedit.example",
      authority: 69,
      backlinks: 2,
      relations: cleanRelations,
      firstSeenAt: "2025-11-11T00:00:00.000Z",
      lastSeenAt: "2025-12-01T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "provider_aggregate",
      anchors: [
        { text: "Niche Perfume", count: 1, classification: "exact" },
        { text: "niche perfume", count: 1, classification: "exact" },
      ],
      targetUrls: ["https://example.test/collections/niche-fragrance"],
    },
    {
      domain: "couponwire.example",
      authority: 25,
      backlinks: 1,
      relations: { dofollow: false, nofollow: true, sponsored: false, ugc: false },
      firstSeenAt: "2026-01-20T00:00:00.000Z",
      lastSeenAt: null,
      lostAt: null,
      change30d: "unknown",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "shop now", count: 1, classification: "generic" }],
      targetUrls: ["https://example.test/"],
    },
  ],
};

export const P5_5_NULL_AUTHORITY_PROFILE: BacklinkProfileInput = {
  targetDomain: "null-authority.test",
  summary: {
    authority: null,
    referringDomains: 0,
    backlinks: 0,
    dofollowReferringDomains: 0,
    nofollowReferringDomains: 0,
    sponsoredReferringDomains: 0,
    ugcReferringDomains: 0,
    newReferringDomains30d: 0,
    lostReferringDomains30d: 0,
  },
  referringDomains: [],
};

export const P5_5_ZERO_AUTHORITY_PROFILE: BacklinkProfileInput = {
  targetDomain: "zero-authority.test",
  summary: {
    authority: 0,
    referringDomains: 0,
    backlinks: 0,
    dofollowReferringDomains: 0,
    nofollowReferringDomains: 0,
    sponsoredReferringDomains: 0,
    ugcReferringDomains: 0,
    newReferringDomains30d: 0,
    lostReferringDomains30d: 0,
  },
  referringDomains: [],
};

export const P5_5_FRESHNESS_CHURN_PROFILE: BacklinkProfileInput = {
  targetDomain: "freshness.test",
  summary: {
    authority: 50,
    referringDomains: 4,
    backlinks: 4,
    dofollowReferringDomains: 4,
    nofollowReferringDomains: 0,
    sponsoredReferringDomains: 0,
    ugcReferringDomains: 0,
    newReferringDomains30d: 1,
    lostReferringDomains30d: 1,
  },
  referringDomains: [
    {
      domain: "fresh.example",
      authority: 60,
      backlinks: 1,
      relations: cleanRelations,
      firstSeenAt: "2026-09-10T00:00:00.000Z",
      lastSeenAt: "2026-09-10T00:00:00.000Z",
      lostAt: null,
      change30d: "new",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "fresh", count: 1, classification: "other" }],
      targetUrls: ["https://freshness.test/"],
    },
    {
      domain: "recent.example",
      authority: 55,
      backlinks: 1,
      relations: cleanRelations,
      firstSeenAt: "2026-01-01T00:00:00.000Z",
      lastSeenAt: "2026-07-20T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "recent", count: 1, classification: "other" }],
      targetUrls: ["https://freshness.test/"],
    },
    {
      domain: "aging.example",
      authority: 45,
      backlinks: 1,
      relations: cleanRelations,
      firstSeenAt: "2025-12-01T00:00:00.000Z",
      lastSeenAt: "2026-05-01T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "aging", count: 1, classification: "other" }],
      targetUrls: ["https://freshness.test/"],
    },
    {
      domain: "stale.example",
      authority: 35,
      backlinks: 1,
      relations: cleanRelations,
      firstSeenAt: "2025-01-01T00:00:00.000Z",
      lastSeenAt: "2025-12-01T00:00:00.000Z",
      lostAt: "2026-09-01T00:00:00.000Z",
      change30d: "lost",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "stale", count: 1, classification: "other" }],
      targetUrls: ["https://freshness.test/"],
    },
  ],
};

export const P5_5_GAP_OWNED_PROFILE: BacklinkProfileInput = {
  targetDomain: "owned.test",
  summary: {
    authority: 61,
    referringDomains: 2,
    backlinks: 2,
    dofollowReferringDomains: 2,
    nofollowReferringDomains: 0,
    sponsoredReferringDomains: 0,
    ugcReferringDomains: 0,
    newReferringDomains30d: 0,
    lostReferringDomains30d: 0,
  },
  referringDomains: [
    {
      domain: "owned-only.example",
      authority: 53,
      backlinks: 1,
      relations: cleanRelations,
      firstSeenAt: "2026-01-01T00:00:00.000Z",
      lastSeenAt: "2026-09-10T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "owned", count: 1, classification: "brand" }],
      targetUrls: ["https://owned.test/"],
    },
    {
      domain: "shared-owned.example",
      authority: 70,
      backlinks: 1,
      relations: cleanRelations,
      firstSeenAt: "2026-01-01T00:00:00.000Z",
      lastSeenAt: "2026-09-11T00:00:00.000Z",
      lostAt: null,
      change30d: "unchanged",
      anchorCountBasis: "backlink_count",
      anchors: [{ text: "owned shared", count: 1, classification: "partial" }],
      targetUrls: ["https://owned.test/category"],
    },
  ],
};

export const P5_5_GAP_COMPETITOR_PROFILES: BacklinkProfileInput[] = [
  {
    targetDomain: "competitor-a.test",
    summary: {
      authority: 66,
      referringDomains: 4,
      backlinks: 5,
      dofollowReferringDomains: 4,
      nofollowReferringDomains: 0,
      sponsoredReferringDomains: 0,
      ugcReferringDomains: 0,
      newReferringDomains30d: 0,
      lostReferringDomains30d: 0,
    },
    referringDomains: [
      {
        domain: "editorial-a.example",
        authority: 82,
        backlinks: 2,
        relations: cleanRelations,
        firstSeenAt: "2026-01-01T00:00:00.000Z",
        lastSeenAt: "2026-09-12T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "provider_aggregate",
        anchors: [{ text: "competitor a", count: 2, classification: "brand" }],
        targetUrls: ["https://competitor-a.test/"],
      },
      {
        domain: "editorial-b.example",
        authority: 67,
        backlinks: 1,
        relations: cleanRelations,
        firstSeenAt: "2026-02-01T00:00:00.000Z",
        lastSeenAt: "2026-09-01T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "backlink_count",
        anchors: [{ text: "editorial b", count: 1, classification: "other" }],
        targetUrls: ["https://competitor-a.test/"],
      },
      {
        domain: "single-a.example",
        authority: 45,
        backlinks: 1,
        relations: cleanRelations,
        firstSeenAt: "2026-03-01T00:00:00.000Z",
        lastSeenAt: "2026-08-25T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "backlink_count",
        anchors: [{ text: "single a", count: 1, classification: "other" }],
        targetUrls: ["https://competitor-a.test/"],
      },
      {
        domain: "shared-owned.example",
        authority: 70,
        backlinks: 1,
        relations: cleanRelations,
        firstSeenAt: "2026-01-01T00:00:00.000Z",
        lastSeenAt: "2026-09-11T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "backlink_count",
        anchors: [{ text: "shared", count: 1, classification: "other" }],
        targetUrls: ["https://competitor-a.test/"],
      },
    ],
  },
  {
    targetDomain: "competitor-b.test",
    summary: {
      authority: 63,
      referringDomains: 3,
      backlinks: 4,
      dofollowReferringDomains: 3,
      nofollowReferringDomains: 0,
      sponsoredReferringDomains: 0,
      ugcReferringDomains: 0,
      newReferringDomains30d: 0,
      lostReferringDomains30d: 0,
    },
    referringDomains: [
      {
        domain: "editorial-a.example",
        authority: 82,
        backlinks: 1,
        relations: cleanRelations,
        firstSeenAt: "2026-01-01T00:00:00.000Z",
        lastSeenAt: "2026-09-12T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "backlink_count",
        anchors: [{ text: "competitor b", count: 1, classification: "brand" }],
        targetUrls: ["https://competitor-b.test/"],
      },
      {
        domain: "editorial-b.example",
        authority: 67,
        backlinks: 2,
        relations: cleanRelations,
        firstSeenAt: "2026-02-01T00:00:00.000Z",
        lastSeenAt: "2026-09-01T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "provider_aggregate",
        anchors: [{ text: "editorial b", count: 2, classification: "other" }],
        targetUrls: ["https://competitor-b.test/"],
      },
      {
        domain: "shared-owned.example",
        authority: 70,
        backlinks: 1,
        relations: cleanRelations,
        firstSeenAt: "2026-01-01T00:00:00.000Z",
        lastSeenAt: "2026-09-11T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "backlink_count",
        anchors: [{ text: "shared", count: 1, classification: "other" }],
        targetUrls: ["https://competitor-b.test/"],
      },
    ],
  },
  {
    targetDomain: "competitor-c.test",
    summary: {
      authority: 60,
      referringDomains: 1,
      backlinks: 1,
      dofollowReferringDomains: 1,
      nofollowReferringDomains: 0,
      sponsoredReferringDomains: 0,
      ugcReferringDomains: 0,
      newReferringDomains30d: 0,
      lostReferringDomains30d: 0,
    },
    referringDomains: [
      {
        domain: "editorial-a.example",
        authority: 82,
        backlinks: 1,
        relations: cleanRelations,
        firstSeenAt: "2026-01-01T00:00:00.000Z",
        lastSeenAt: "2026-09-12T00:00:00.000Z",
        lostAt: null,
        change30d: "unchanged",
        anchorCountBasis: "backlink_count",
        anchors: [{ text: "competitor c", count: 1, classification: "brand" }],
        targetUrls: ["https://competitor-c.test/"],
      },
    ],
  },
];
