import { createHash } from "node:crypto";
import { buildControlledGitPlan, type ControlledGitPlan } from "./controlled-git-connector.js";

export const UGP_GIT_CERTIFICATION_VERSION="ugp-4-7-git-certification-v2" as const;
const SHA=/^[0-9a-f]{40}$/; const SHA256=/^[0-9a-f]{64}$/; const REPO=/^[A-Za-z0-9_.-]{1,100}\/[A-Za-z0-9_.-]{1,100}$/;
function stable(v:unknown):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return "["+v.map(stable).join(",")+"]";const o=v as Record<string,unknown>;return "{"+Object.keys(o).sort().map(k=>JSON.stringify(k)+":"+stable(o[k])).join(",")+"}";}
function hash(v:unknown){return createHash("sha256").update(stable(v)).digest("hex");}
function exact(v:unknown,re:RegExp,f:string){if(typeof v!=="string"||v!==v.trim()||!re.test(v))throw new Error("ugp_git_cert_invalid_"+f);return v;}
export type GitCertificationEvidence=Readonly<{repository:string;defaultBranch:string;baseCommitSha:string;filePath:string;observedBlobSha:string;changePath?:string;resultingBlobSha?:string;workingBranch:string;resultingCommitSha:string;pullRequestNumber:number;pullRequestHeadSha:string;ciCommitSha:string;ciConclusion:"success";proposedContentFingerprint:string}>;
export type GitCertificationReceipt=Readonly<{version:typeof UGP_GIT_CERTIFICATION_VERSION;planFingerprint:string;repositoryRead:Readonly<{repository:string;ref:string;commitSha:string;path:string;blobSha:string;readOnly:true}>;patch:Readonly<{path:string;expectedBlobSha:string|null;resultingBlobSha:string|null;proposedContentFingerprint:string;deterministic:true}>;change:Readonly<{workingBranch:string;resultingCommitSha:string;pullRequestNumber:number;pullRequestHeadSha:string;defaultBranchWrite:false;mergePerformed:false}>;ci:Readonly<{commitSha:string;conclusion:"success";readOnly:true}>;assertions:Readonly<{capturedEvidenceOnly:true;networkCalls:false;credentials:false;forcePush:false;defaultBranchWrite:false;merge:false;deployment:false;publication:false;grantsAuthorization:false}>;receiptFingerprint:string}>;
export function attestGitCertification(input:{plan:ControlledGitPlan;evidence:GitCertificationEvidence}):GitCertificationReceipt{
 const rebuilt=buildControlledGitPlan({descriptor:input.plan.descriptor,repository:input.plan.repository.repository,defaultBranch:input.plan.repository.defaultBranch,baseCommitSha:input.plan.repository.baseCommitSha,workingBranch:input.plan.change.workingBranch,detection:input.plan.detection,patches:input.plan.change.patches});
 if(stable(rebuilt)!==stable(input.plan))throw new Error("ugp_git_cert_plan_integrity_failed");
 const e=input.evidence,repository=exact(e.repository,REPO,"repository"),base=exact(e.baseCommitSha,SHA,"base_commit_sha"),blob=exact(e.observedBlobSha,SHA,"blob_sha"),result=exact(e.resultingCommitSha,SHA,"resulting_commit_sha"),prHead=exact(e.pullRequestHeadSha,SHA,"pr_head_sha"),ci=exact(e.ciCommitSha,SHA,"ci_commit_sha"),fp=exact(e.proposedContentFingerprint,SHA256,"content_fingerprint"),changePath=e.changePath??e.filePath,resultingBlob=e.resultingBlobSha===undefined?null:exact(e.resultingBlobSha,SHA,"resulting_blob_sha");
 if(repository!==input.plan.repository.repository||e.defaultBranch!==input.plan.repository.defaultBranch||base!==input.plan.repository.baseCommitSha)throw new Error("ugp_git_cert_repository_state_drift");
 if(e.workingBranch!==input.plan.change.workingBranch||e.workingBranch===e.defaultBranch)throw new Error("ugp_git_cert_branch_drift");
 const patch=input.plan.change.patches.find(p=>p.path===changePath);if(!patch||patch.proposedContentFingerprint!==fp)throw new Error("ugp_git_cert_patch_drift");if(patch.expectedBlobSha===null){if(changePath===e.filePath||!resultingBlob)throw new Error("ugp_git_cert_create_evidence_invalid");}else if(changePath!==e.filePath||patch.expectedBlobSha!==blob||resultingBlob!==null)throw new Error("ugp_git_cert_patch_drift");
 if(!Number.isSafeInteger(e.pullRequestNumber)||e.pullRequestNumber<1)throw new Error("ugp_git_cert_invalid_pr_number");
 if(prHead!==result||ci!==result||e.ciConclusion!=="success")throw new Error("ugp_git_cert_head_or_ci_drift");
 const baseReceipt={version:UGP_GIT_CERTIFICATION_VERSION,planFingerprint:input.plan.planFingerprint,repositoryRead:{repository,ref:e.defaultBranch,commitSha:base,path:e.filePath,blobSha:blob,readOnly:true as const},patch:{path:changePath,expectedBlobSha:patch.expectedBlobSha,resultingBlobSha:resultingBlob,proposedContentFingerprint:fp,deterministic:true as const},change:{workingBranch:e.workingBranch,resultingCommitSha:result,pullRequestNumber:e.pullRequestNumber,pullRequestHeadSha:prHead,defaultBranchWrite:false as const,mergePerformed:false as const},ci:{commitSha:ci,conclusion:"success" as const,readOnly:true as const},assertions:{capturedEvidenceOnly:true as const,networkCalls:false as const,credentials:false as const,forcePush:false as const,defaultBranchWrite:false as const,merge:false as const,deployment:false as const,publication:false as const,grantsAuthorization:false as const}};
 return Object.freeze({...baseReceipt,receiptFingerprint:hash({purpose:"ugp_git_certification_receipt",...baseReceipt})});
}
