import assert from "node:assert/strict";
import test from "node:test";
import { W09_C2Z_SCHEMA_VERSION, produceRailwayNeonBindingIdentity, type RailwayNeonProducerContext } from "./p8-8-w09c2z-railway-neon-binding-producer.js";
import { verifySanitizedPlatformBindingAttestation, type VerifyPlatformAttestationContext } from "./p8-8-w09c2w-platform-attestation-verifier.js";

const context: RailwayNeonProducerContext={expectedRailwayProjectId:"rp",expectedRailwayEnvironmentId:"re",expectedRailwayServiceId:"rs",expectedRailwayDeploymentId:"rd",expectedRailwaySnapshotId:"snap",expectedProvider:"Neon"};
const fixture=()=>({schemaVersion:W09_C2Z_SCHEMA_VERSION,provenanceKind:"synthetic_join",provenanceAuthority:"synthetic.broker",railwayProjectId:"rp",railwayEnvironmentId:"re",railwayServiceId:"rs",railwayDeploymentId:"rd",railwayDeploymentStatus:"SUCCESS",railwaySnapshotId:"snap",railwayPublicUrl:"https://synthetic.invalid",railwayBindingRevisionId:"rev",structuralReferenceId:"ref",structuralReferenceTargetResourceId:"resource",provider:"Neon",providerProjectId:"np",branchId:"nb",databaseName:"db",timelineId:"nt",endpointId:"ne",providerResourceId:"resource",observedAt:"2030-01-01T00:00:00.000Z"});

test("exact synthetic join is deterministic",()=>{const a=produceRailwayNeonBindingIdentity(fixture(),context),b=produceRailwayNeonBindingIdentity(fixture(),context);assert.deepEqual(a,b);assert.equal(a.verdict,"PASS");assert.equal(a.identity?.platformKind,"railway");});
test("producer cannot self-approve provenance",()=>{const p=produceRailwayNeonBindingIdentity(fixture(),context);const c:VerifyPlatformAttestationContext={expectedPlatformKind:"railway",expectedPlatformSubjectId:"rs",expectedDeploymentId:"rd",expectedProvider:"Neon",approvedProvenanceKinds:[],approvedProvenanceAuthorities:[],observedAt:"2030-01-01T00:00:30.000Z",maxAgeMs:60000};assert.equal(verifySanitizedPlatformBindingAttestation(p.identity,c).code,"ATTESTATION_PROVENANCE_UNAPPROVED");c.approvedProvenanceKinds=["synthetic_join"];c.approvedProvenanceAuthorities=["synthetic.broker"];assert.equal(verifySanitizedPlatformBindingAttestation(p.identity,c).verdict,"PASS");});
test("credential contamination rejected without echo",()=>{const v:Record<string,unknown>=fixture();v.DATABASE_URL="postgresql://user:pass@invalid/db";const r=produceRailwayNeonBindingIdentity(v,context);assert.equal(r.code,"PRODUCER_CREDENTIAL_SHAPED_INPUT");assert.doesNotMatch(JSON.stringify(r),/postgresql|pass/);});
test("unknown field rejected",()=>{const v:Record<string,unknown>=fixture();v.extra="x";assert.equal(produceRailwayNeonBindingIdentity(v,context).code,"PRODUCER_UNKNOWN_FIELD");});
test("Railway identity status snapshot binding fail closed",()=>{const a=fixture();a.railwayServiceId="x";assert.equal(produceRailwayNeonBindingIdentity(a,context).code,"PRODUCER_RAILWAY_IDENTITY_UNPROVED");const b=fixture();b.railwayDeploymentStatus="FAILED";assert.equal(produceRailwayNeonBindingIdentity(b,context).code,"PRODUCER_DEPLOYMENT_NOT_SUCCESS");const c=fixture();c.railwaySnapshotId="x";assert.equal(produceRailwayNeonBindingIdentity(c,context).code,"PRODUCER_SNAPSHOT_UNPROVED");const d=fixture();d.railwayBindingRevisionId="";assert.equal(produceRailwayNeonBindingIdentity(d,context).code,"PRODUCER_BINDING_UNPROVED");});
test("reference and cross-side agreement mandatory",()=>{const a=fixture();a.structuralReferenceId="";assert.equal(produceRailwayNeonBindingIdentity(a,context).code,"PRODUCER_REFERENCE_UNPROVED");const b=fixture();b.structuralReferenceTargetResourceId="x";assert.equal(produceRailwayNeonBindingIdentity(b,context).code,"PRODUCER_CROSS_SIDE_MISMATCH");});
test("provider and lineage fail closed",()=>{const a=fixture();a.provider="Other";assert.equal(produceRailwayNeonBindingIdentity(a,context).code,"PRODUCER_PROVIDER_MISMATCH");const b=fixture();b.providerProjectId="";assert.equal(produceRailwayNeonBindingIdentity(b,context).code,"PRODUCER_PROVIDER_IDENTITY_UNPROVED");const c=fixture();c.timelineId="";assert.equal(produceRailwayNeonBindingIdentity(c,context).code,"PRODUCER_LINEAGE_UNPROVED");});
