import assert from "node:assert/strict";
import test from "node:test";
import {attestCapturedWebflowEvidence,type CapturedWebflowObservation} from "./webflow-captured-evidence-attestation.js";

function observations():CapturedWebflowObservation[]{return [
 {resource:"pages",effectiveUrl:"https://api.webflow.com/v2/sites/6ab94b0baca74bd07f84a09e/pages",status:200,contentType:"application/json; charset=utf-8",responseBytes:576,payload:{pages:[{id:"page-1",title:"Home"}]}},
 {resource:"collections",effectiveUrl:"https://api.webflow.com/v2/sites/6ab94b0baca74bd07f84a09e/collections",status:200,contentType:"application/json; charset=utf-8",responseBytes:214,payload:{collections:[{id:"collection-1",displayName:"Test Articles"}]}}
];}

test("UGP-4.6L-R deterministically attests exact captured resource set offline",()=>{const a=attestCapturedWebflowEvidence({observations:observations()});const b=attestCapturedWebflowEvidence({observations:observations()});assert.deepEqual(a,b);assert.equal(a.siteId,"6ab94b0baca74bd07f84a09e");assert.equal(a.receipts.length,2);assert.deepEqual(a.assertions,{offlineOnly:true,networkCalls:false,getOnly:true,credentials:false,providerWrites:false,publicSiteWrites:false,persistence:false});for(const x of a.receipts){assert.match(x.receipt.requestFingerprint,/^[0-9a-f]{64}$/);assert.match(x.receipt.stateFingerprint,/^[0-9a-f]{64}$/);assert.match(x.receipt.receiptFingerprint,/^[0-9a-f]{64}$/);}});
test("UGP-4.6L-R fails closed on resource set and acquisition metadata",()=>{const good=observations();assert.throws(()=>attestCapturedWebflowEvidence({observations:[good[0]]}),/exact_two/);assert.throws(()=>attestCapturedWebflowEvidence({observations:[good[0],{...good[1],resource:"pages"}]}),/resource_set/);for(const changed of [{effectiveUrl:"https://evil.example/v2/sites/6ab94b0baca74bd07f84a09e/collections"},{status:500},{status:403},{contentType:"text/html"},{responseBytes:1000001}]){const x=observations();x[1]={...x[1],...changed};assert.throws(()=>attestCapturedWebflowEvidence({observations:x}));}});
test("UGP-4.6L-R rejects non-JSON or oversized normalized payloads",()=>{const x=observations();x[1]={...x[1],payload:{bad:undefined}};assert.throws(()=>attestCapturedWebflowEvidence({observations:x}),/non_json_payload/);const y=observations();y[1]={...y[1],payload:"x".repeat(1_000_001)};assert.throws(()=>attestCapturedWebflowEvidence({observations:y}),/payload_too_large/);});
test("UGP-4.6L-R payload tampering changes deterministic evidence fingerprints",()=>{const a=attestCapturedWebflowEvidence({observations:observations()});const changed=observations();changed[0]={...changed[0],payload:{pages:[{id:"page-1",title:"Changed"}]}};const b=attestCapturedWebflowEvidence({observations:changed});assert.notEqual(a.receipts[0].receipt.stateFingerprint,b.receipts[0].receipt.stateFingerprint);assert.notEqual(a.receipts[0].receipt.receiptFingerprint,b.receipts[0].receipt.receiptFingerprint);});
