import assert from "node:assert/strict";
import test from "node:test";
import {buildUniversalSiteIdentity,buildUniversalConnectionIdentity} from "./universal-site-resource-identity.js";
import {buildUniversalCapabilityRegistry} from "./universal-capability-registry.js";
import {buildUniversalConnectorDescriptor} from "./universal-connector-contract.js";
import {buildWordPressReadPlan,normalizeWordPressReadReceipt} from "./wordpress-read-provider-certification.js";

function descriptor(origin="https://example.com"){
 const site=buildUniversalSiteIdentity({siteId:"wp-site",canonicalOrigin:origin});
 const connection=buildUniversalConnectionIdentity({site,connectionId:"wp-rest-1",provider:"wordpress",externalAccountId:"wp-site-1",connectionMode:"api"});
 const registry=buildUniversalCapabilityRegistry({site,connection,provider:"wordpress",connectorVersion:"wordpress-rest-cert-v1",credentialProfileId:"credential-profile-ref",capabilities:[
 {capability:"read.resource",resourceKinds:["page","article"],requiredProviderScopes:["content:read"],verification:"not_applicable",rollback:"not_applicable",maxOperationsPerRequest:100,maxPayloadBytes:1000000},
 {capability:"read.content",resourceKinds:["page","article"],requiredProviderScopes:["content:read"],verification:"not_applicable",rollback:"not_applicable",maxOperationsPerRequest:100,maxPayloadBytes:1000000}]});
 return buildUniversalConnectorDescriptor({connectorId:"wordpress-rest-read",connectorKind:"native_api",registry});
}
test("UGP-4.5 deterministically binds WordPress GET page reads",()=>{const a=buildWordPressReadPlan({descriptor:descriptor(),method:"GET",route:"/wp-json/wp/v2/pages",resourceKind:"page",capability:"read.content",maxResults:20});const b=buildWordPressReadPlan({descriptor:descriptor(),method:"GET",route:"/wp-json/wp/v2/pages",resourceKind:"page",capability:"read.content",maxResults:20});assert.equal(a.requestFingerprint,b.requestFingerprint);assert.deepEqual(a.semantics,{fixtureCertificationOnly:true,liveTransportEnabled:false,credentialMaterialAccepted:false,grantsAuthorization:false,providerWrites:false,publicSiteWrites:false});});
test("UGP-4.5 normalizes caller-supplied WordPress evidence",()=>{const p=buildWordPressReadPlan({descriptor:descriptor(),method:"GET",route:"/wp-json/wp/v2/posts",resourceKind:"article",capability:"read.resource",maxResults:10});const r=normalizeWordPressReadReceipt({plan:p,effectiveUrl:"https://example.com/wp-json/wp/v2/posts",status:200,payload:[{id:7,slug:"hello"}]});assert.equal(r.status,200);assert.equal(r.requestFingerprint,p.requestFingerprint);assert.match(r.stateFingerprint,/^[0-9a-f]{64}$/);assert.ok(Object.isFrozen(r));});
test("UGP-4.5 fails closed on route/resource and effective URL drift",()=>{assert.throws(()=>buildWordPressReadPlan({descriptor:descriptor(),method:"GET",route:"/wp-json/wp/v2/pages",resourceKind:"article",capability:"read.content",maxResults:10}),/route_resource_mismatch/);const p=buildWordPressReadPlan({descriptor:descriptor(),method:"GET",route:"/wp-json/wp/v2/pages",resourceKind:"page",capability:"read.content",maxResults:10});assert.throws(()=>normalizeWordPressReadReceipt({plan:p,effectiveUrl:"https://evil.example/wp-json/wp/v2/pages",status:200,payload:[]}),/effective_url_drift/);});
test("UGP-4.5 rejects noncanonical HTTP origin",()=>{assert.throws(()=>buildWordPressReadPlan({descriptor:descriptor("http://example.com"),method:"GET",route:"/wp-json/wp/v2/pages",resourceKind:"page",capability:"read.content",maxResults:10}),/https_canonical_origin_required/);});
test("UGP-4.5 rejects malformed or oversized evidence",()=>{const p=buildWordPressReadPlan({descriptor:descriptor(),method:"GET",route:"/wp-json/wp/v2/pages",resourceKind:"page",capability:"read.content",maxResults:10});assert.throws(()=>normalizeWordPressReadReceipt({plan:p,effectiveUrl:"https://example.com/wp-json/wp/v2/pages",status:500,payload:[]}),/status_not_ok/);assert.throws(()=>normalizeWordPressReadReceipt({plan:p,effectiveUrl:"https://example.com/wp-json/wp/v2/pages",status:200,payload:{bad:undefined}}),/non_json_payload/);assert.throws(()=>normalizeWordPressReadReceipt({plan:p,effectiveUrl:"https://example.com/wp-json/wp/v2/pages",status:200,payload:"x".repeat(1_000_001)}),/payload_too_large/);});
