import assert from "node:assert/strict";
import test from "node:test";
import {buildUniversalSiteIdentity,buildUniversalConnectionIdentity} from "./universal-site-resource-identity.js";
import {buildUniversalCapabilityRegistry} from "./universal-capability-registry.js";
import {buildUniversalConnectorDescriptor} from "./universal-connector-contract.js";
import {runAuthorizedWordPressLiveEvidence,UGP_WORDPRESS_LIVE_ALLOWED_ORIGIN,type WordPressLiveTransport} from "./wordpress-live-evidence-runner.js";

function descriptor(origin=UGP_WORDPRESS_LIVE_ALLOWED_ORIGIN){const site=buildUniversalSiteIdentity({siteId:"wp-live-site",canonicalOrigin:origin});const connection=buildUniversalConnectionIdentity({site,connectionId:"wp-live-rest",provider:"wordpress",externalAccountId:"wp-live",connectionMode:"api"});const registry=buildUniversalCapabilityRegistry({site,connection,provider:"wordpress",connectorVersion:"wordpress-rest-cert-v1",credentialProfileId:"no-live-credential",capabilities:[{capability:"read.content",resourceKinds:["page","article"],requiredProviderScopes:["content:read"],verification:"not_applicable",rollback:"not_applicable",maxOperationsPerRequest:100,maxPayloadBytes:1000000}]});return buildUniversalConnectorDescriptor({connectorId:"wordpress-live-read",connectorKind:"native_api",registry});}
function transport(overrides:Partial<Awaited<ReturnType<WordPressLiveTransport>>>={}):WordPressLiveTransport{return async req=>({effectiveUrl:req.url,status:200,contentType:"application/json; charset=UTF-8",payload:[],responseBytes:2,redirected:false,...overrides});}
test("UGP-4.5L executes exactly two bounded credential-free GET observations",async()=>{const seen:string[]=[];const t:WordPressLiveTransport=async req=>{seen.push(JSON.stringify(req));return {effectiveUrl:req.url,status:200,contentType:"application/json",payload:[],responseBytes:2,redirected:false};};const result=await runAuthorizedWordPressLiveEvidence({descriptor:descriptor(),transport:t});assert.equal(result.receipts.length,2);assert.deepEqual(result.assertions,{getOnly:true,credentialsOmitted:true,redirectsDenied:true,providerWrites:false,publicSiteWrites:false,persistence:false});for(const raw of seen){const r=JSON.parse(raw);assert.equal(r.method,"GET");assert.equal(r.redirect,"manual");assert.equal(r.credentials,"omit");assert.equal(r.timeoutMs,10000);assert.equal(r.maxResponseBytes,1000000);}assert.match(seen[0],/wp-json\\\/wp\\\/v2\\\/pages/);assert.match(seen[1],/wp-json\\\/wp\\\/v2\\\/posts/);});
test("UGP-4.5L rejects any unapproved origin",async()=>{await assert.rejects(runAuthorizedWordPressLiveEvidence({descriptor:descriptor("https://example.com"),transport:transport()}),/origin_not_authorized/);});
test("UGP-4.5L fails closed on redirects, auth, content type, status and bounds",async()=>{for(const [t,re] of [[transport({redirected:true}),/redirect_or_origin_drift/],[transport({status:401}),/auth_required/],[transport({contentType:"text/html"}),/json_required/],[transport({status:500}),/status_not_ok/],[transport({responseBytes:1000001}),/response_bounds/]] as const){await assert.rejects(runAuthorizedWordPressLiveEvidence({descriptor:descriptor(),transport:t}),re);}});
