import { Router, type IRouter } from "express";
import { startUrl, seal, open, assertOAuthState, discoverGoogleResources, autoMatchDiamondShelf, exchangeGoogleCode, exchangeShopifyCode, save, list, selectGoogleProperties, GOOGLE_STATE_COOKIE, SHOPIFY_STATE_COOKIE, origin } from "../lib/oauth";

const router: IRouter = Router();
const blocked = () => process.env.PUBLIC_SITE_WRITES_ENABLED?.trim().toLowerCase() === "true";
router.get("/connections/status", async (_req, res) => { try { const rows = await list() as Array<{ provider: string; status: string; metadata: Record<string, unknown> }>; const latest = (p: string) => rows.find((r) => r.provider === p); const shop = latest("shopify"); const google = latest("google"); const needsConfirmation = google?.status === "pending_confirmation" && google.metadata.needsConfirmation === true; return res.json({ readOnly: !blocked(), shopify: { connected: shop?.status === "connected", ...(typeof shop?.metadata.shopDomain === "string" ? { domain: shop.metadata.shopDomain } : {}) }, google: { connected: google?.status === "connected", needsConfirmation, ...(typeof google?.metadata.email === "string" ? { email: google.metadata.email } : {}), ...(needsConfirmation && Array.isArray(google?.metadata.discoveredSearchConsoleProperties) ? { searchConsoleProperties: google.metadata.discoveredSearchConsoleProperties } : {}), ...(needsConfirmation && Array.isArray(google?.metadata.discoveredGa4Properties) ? { ga4Properties: google.metadata.discoveredGa4Properties } : {}) } }); } catch { return res.status(503).json({ error: "Connection status is unavailable." }); } });
router.get("/connections/shopify/start", (req, res) => { try { if (blocked()) throw new Error(); const shop = String(req.query.shop ?? "").trim().toLowerCase(); if (!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/.test(shop)) throw new Error(); const { state, url } = startUrl("shopify", shop); res.cookie(SHOPIFY_STATE_COOKIE, seal(state), { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", maxAge: 600000, path: "/" }); return res.redirect(url); } catch { return res.redirect(`${origin()}/connections?error=Unable%20to%20start%20Shopify%20connection`); } });
router.get("/connections/google/start", (req, res) => { try { if (blocked()) throw new Error(); const { state, url } = startUrl("google"); res.cookie(GOOGLE_STATE_COOKIE, seal(state), { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", maxAge: 600000, path: "/" }); return res.redirect(url); } catch { return res.redirect(`${origin()}/connections?error=Unable%20to%20start%20Google%20connection`); } });
router.get("/connections/shopify/callback", async (req, res) => { try { if (blocked()) throw new Error(); const shop = String(req.query.shop ?? "").toLowerCase(); if (!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/.test(shop)) throw new Error(); const state = open(req.cookies[SHOPIFY_STATE_COOKIE]); assertOAuthState(state, String(req.query.state ?? ""), "shopify"); if (state.shopDomain !== shop) throw new Error(); const config = { clientId: process.env.SHOPIFY_OAUTH_CLIENT_ID!, clientSecret: process.env.SHOPIFY_OAUTH_CLIENT_SECRET!, redirectUri: `${origin()}/api/connections/shopify/callback`, shopDomain: state.shopDomain! }; await save("shopify", state.shopDomain!, await exchangeShopifyCode(config, String(req.query.code)), { shopDomain: shop }); res.clearCookie(SHOPIFY_STATE_COOKIE); return res.redirect(`${origin()}/connections?success=shopify`); } catch { return res.redirect(`${origin()}/connections?error=Shopify%20connection%20failed`); } });
router.get("/connections/google/callback", async (req, res) => { try { if (blocked()) throw new Error(); const state = open(req.cookies[GOOGLE_STATE_COOKIE]); assertOAuthState(state, String(req.query.state ?? ""), "google"); const config = { clientId: process.env.GOOGLE_OAUTH_CLIENT_ID!, clientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET!, redirectUri: `${origin()}/api/connections/google/callback` }; const bundle = await exchangeGoogleCode(config, String(req.query.code), state); if (!bundle.refreshToken) throw new Error(); const discovered = await discoverGoogleResources(bundle.accessToken); const match = autoMatchDiamondShelf(discovered); await save("google", "google", bundle, { connectionMode: "oauth", readOnly: true, discoveredSearchConsoleProperties: discovered.searchConsoleProperties, discoveredGa4Properties: discovered.ga4Properties, gscSiteUrl: match.gscSiteUrl, ga4PropertyId: match.ga4PropertyId, needsConfirmation: match.needsConfirmation }, match.needsConfirmation ? "pending_confirmation" : "connected"); if (!match.needsConfirmation) res.clearCookie(GOOGLE_STATE_COOKIE); return res.redirect(`${origin()}/connections?success=${match.needsConfirmation ? "google_pending" : "google"}`); } catch { return res.redirect(`${origin()}/connections?error=Google%20connection%20failed`); } });
router.post("/connections/google/select", async (req, res) => { try { if (blocked()) throw new Error(); const state = open(req.cookies[GOOGLE_STATE_COOKIE]); assertOAuthState(state, state.state, "google"); const gsc = String(req.body?.gscSiteUrl ?? "").trim(); const ga4 = String(req.body?.ga4PropertyId ?? "").trim(); if (!/^https:\/\/diamondshelf\.us\/?$/i.test(gsc) || !/^\d+$/.test(ga4)) throw new Error(); await selectGoogleProperties(gsc, ga4); res.clearCookie(GOOGLE_STATE_COOKIE); return res.redirect(`${origin()}/connections?success=google`); } catch { return res.redirect(`${origin()}/connections?error=Unable%20to%20save%20Google%20property%20selection`); } });
export default router;