import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { P12_2_L9_2B_ENVIRONMENT_ID,P12_2_L9_2B_EXPECTED_TABLE_COUNT,P12_2_L9_2B_MIGRATION_BLOB_SHA,P12_2_L9_2B_MIGRATION_PATH,P12_2_L9_2B_MIGRATION_SHA256,P12_2_L9_2B_ORIGIN,P12_2_L9_2B_POSTGRES_SERVICE_ID,P12_2_L9_2B_PROJECT_ID,P12_2_L9_2B_SITE_ID,P12_2_L9_2B_VERSION,p122L92BAuthorizationFingerprint,p122L92BAuthorizationLiteral } from "./lib/p12-2-l9-2b-0009-apply-contract.js";
import { assertP122L1AE9NoCredentialArgv,buildP122L1AE9PsqlConnectionEnv } from "./lib/p12-2-l1a-e9-runtime-transport.js";
const MIGRATION_FILE="/app/0009_first_party_crawl_l2_bounded_pilot_phase.sql"; const MAX_OUTPUT_BYTES=262144;
function required(name:string){const value=process.env[name]?.trim()??"";if(!value)throw new Error("p12_2_l9_2b_missing_env_"+name.toLowerCase());return value;} function exact(a:string,e:string,c:string){if(a!==e)throw new Error(c);}
function wrapperSql(){return ["\\set ON_ERROR_STOP on","\\pset tuples_only on","\\pset format csv",
`SELECT 'preflight_guard',1/CASE WHEN
(SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE')=${P12_2_L9_2B_EXPECTED_TABLE_COUNT}
AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='first_party_crawl_l2_invocations')
AND EXISTS (SELECT 1 FROM pg_catalog.pg_constraint con JOIN pg_catalog.pg_class c ON c.oid=con.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='first_party_crawl_l2_invocations' AND con.conname='first_party_crawl_l2_invocations_phase_check' AND pg_get_constraintdef(con.oid,true) NOT ILIKE '%bounded_pilot%')
AND NOT EXISTS (SELECT 1 FROM first_party_crawl_l2_invocations WHERE phase NOT IN ('full_initial','full_interrupt','full_resume','full_reconciliation','incremental'))
AND EXISTS (SELECT 1 FROM public.sites WHERE id='${P12_2_L9_2B_SITE_ID}'::uuid AND lower(domain)='diamondshelf.us' AND canonical_origin='${P12_2_L9_2B_ORIGIN}' AND is_active=true)
THEN 1 ELSE 0 END;`,
`\\i ${MIGRATION_FILE}`,
"SELECT 'post_table_count',count(*)::int FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE';",
"SELECT 'post_phase_counts',phase,count(*)::int FROM first_party_crawl_l2_invocations GROUP BY phase ORDER BY phase;",
"SELECT 'post_l2_constraints',con.conname,con.contype,pg_get_constraintdef(con.oid,true) FROM pg_catalog.pg_constraint con JOIN pg_catalog.pg_class c ON c.oid=con.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='first_party_crawl_l2_invocations' ORDER BY con.conname;",
`SELECT 'post_guard',1/CASE WHEN
(SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE')=${P12_2_L9_2B_EXPECTED_TABLE_COUNT}
AND EXISTS (SELECT 1 FROM pg_catalog.pg_constraint con JOIN pg_catalog.pg_class c ON c.oid=con.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='first_party_crawl_l2_invocations' AND con.conname='first_party_crawl_l2_invocations_phase_check' AND pg_get_constraintdef(con.oid,true) ILIKE '%bounded_pilot%')
THEN 1 ELSE 0 END;`].join("\n")+"\n";}
async function main(){exact(required("RAILWAY_PROJECT_ID"),P12_2_L9_2B_PROJECT_ID,"p12_2_l9_2b_project_mismatch");exact(required("RAILWAY_ENVIRONMENT_ID"),P12_2_L9_2B_ENVIRONMENT_ID,"p12_2_l9_2b_environment_mismatch");exact(required("P12_2_L9_2B_POSTGRES_SERVICE_ID"),P12_2_L9_2B_POSTGRES_SERVICE_ID,"p12_2_l9_2b_postgres_service_mismatch");exact(required("P12_2_L9_2B_AUTHORIZATION_LITERAL"),p122L92BAuthorizationLiteral(),"p12_2_l9_2b_authorization_mismatch");const databaseUrl=required("DATABASE_URL");if(!/^postgres(?:ql)?:\/\//i.test(databaseUrl))throw new Error("p12_2_l9_2b_database_url_scheme_invalid");const migration=await readFile(MIGRATION_FILE);exact(createHash("sha256").update(migration).digest("hex"),P12_2_L9_2B_MIGRATION_SHA256,"p12_2_l9_2b_migration_sha256_mismatch");const args=["--no-psqlrc","--set","ON_ERROR_STOP=1"];assertP122L1AE9NoCredentialArgv(args,databaseUrl);const childEnv: NodeJS.ProcessEnv={...process.env,...buildP122L1AE9PsqlConnectionEnv(databaseUrl),PGOPTIONS:"-c statement_timeout=15000 -c lock_timeout=5000"};delete childEnv.DATABASE_URL;const startedAt=new Date().toISOString();const result=await new Promise<{exitCode:number;stdout:string;stderr:string;overflow:boolean}>((resolve,reject)=>{const child=spawn("/usr/bin/psql",args,{shell:false,env:childEnv,stdio:["pipe","pipe","pipe"]});let stdout="",stderr="",overflow=false;const add=(cur:string,ch:Buffer)=>{const next=cur+ch.toString("utf8");if(Buffer.byteLength(next,"utf8")>MAX_OUTPUT_BYTES){overflow=true;return next.slice(0,MAX_OUTPUT_BYTES);}return next;};child.stdout.on("data",(c:Buffer)=>{stdout=add(stdout,c);if(overflow)child.kill("SIGTERM");});child.stderr.on("data",(c:Buffer)=>{stderr=add(stderr,c);if(overflow)child.kill("SIGTERM");});child.once("error",reject);child.once("close",code=>resolve({exitCode:overflow?70:(typeof code==="number"?code:71),stdout,stderr,overflow}));child.stdin.end(wrapperSql());});process.stdout.write(JSON.stringify({version:P12_2_L9_2B_VERSION,projectId:P12_2_L9_2B_PROJECT_ID,environmentId:P12_2_L9_2B_ENVIRONMENT_ID,postgresServiceId:P12_2_L9_2B_POSTGRES_SERVICE_ID,migrationPath:P12_2_L9_2B_MIGRATION_PATH,migrationBlobSha:P12_2_L9_2B_MIGRATION_BLOB_SHA,migrationSha256:P12_2_L9_2B_MIGRATION_SHA256,authorizationFingerprint:p122L92BAuthorizationFingerprint(),startedAt,completed:result.exitCode===0&&!result.overflow,exitCode:result.exitCode,stdout:result.stdout,stderr:result.stderr,psqlProcesses:1,attempts:1,retries:0,fallbackTransportUsed:false,credentialMaterialRecorded:false})+"\n");process.exitCode=result.exitCode===0&&!result.overflow?0:1;}
main().catch(error=>{const message=error instanceof Error&&/^[a-z0-9_:-]+$/.test(error.message)?error.message:"p12_2_l9_2b_bounded_failure";process.stderr.write(JSON.stringify({version:P12_2_L9_2B_VERSION,completed:false,error:message,psqlProcessesStarted:0,credentialMaterialRecorded:false})+"\n");process.exitCode=1;});
